name: DeployToGitHubPages
env:
  PROJECT: Blazor.DownloadFileFast
  APP: Blazor.DownloadFileFast.Example
  PUBLISH_DIR: ${{ APP }}/bin/Release/net5.0/publish/wwwroot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '5.0.x'

    - name: Publish app
      run: dotnet publish -c Release ${{ APP }}

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /${{ PROJECT }}/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}