name: DeployToGitHubPages
env:
  PROJECT: Blazor.DownloadFileFast
  APP: Examples/Blazor.DownloadFileFast.Example_NET9
  PUBLISH_DIR: Examples/Blazor.DownloadFileFast.Example_NET9/bin/Release/net9.0/publish/wwwroot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '9.0.x'

    - name: Publish app
      run: dotnet publish -c Release ${{ env.APP }}

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /${{ env.PROJECT }}/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4.1.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}